name: C/C++ CI

on:
  push:
    branches: [ "main" ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:    
    - uses: actions/checkout@v4
    - name: Install GCC
      uses: egor-tensin/setup-gcc@v2
    - name: Build Test
      run: ./make-gcc
